branch-protection:
  orgs:
    janus-idp:
      repos:
        backstage-showcase:
          branches:
            main:
              protect: true
              required_status_checks:
                contexts:
                - Main Job
                - PR Docker Build
            release-1.4:
              protect: true
              required_status_checks:
                contexts:
                - Main Job
                - PR Docker Build
            release-1.3:
              protect: true
              required_status_checks:
                contexts:
                - Main Job
                - PR Docker Build
            1.2.x:
              protect: true
              required_status_checks:
                contexts:
                - Main Job
                - PR Docker Build
          protect: true
          required_status_checks:
            contexts:
tide:
  merge_method:
    janus-idp/backstage-showcase: squash
  queries:
  - excludedBranches:
    - changeset-release/main
    - changeset-release/release-1.4
    - changeset-release/release-1.3
    - changeset-release/1.2.x
    labels:
    - approved
    - lgtm
    missingLabels:
    - backports/unvalidated-commits
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - jira/invalid-bug
    - needs-rebase
    repos:
    - janus-idp/backstage-showcase
