branch-protection:
  orgs:
    janus-idp:
      repos:
        backstage-plugins:
          unmanaged: true
tide:
  merge_method:
    janus-idp/backstage-plugins: squash
  queries:
  - labels:
    - lgtm
    missingLabels:
    - backports/unvalidated-commits
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - jira/invalid-bug
    - needs-rebase
    repos:
    - janus-idp/backstage-plugins
    reviewApprovedRequired: true
