branch-protection:
  orgs:
    janus-idp:
      repos:
        backstage-plugins:
          branches:
            main:
              protect: true
              required_status_checks:
                contexts:
                - Conventional Commits
                - Test with Node.js 20
                - Build with Node.js 20
            release-1.4:
              protect: true
              required_status_checks:
                contexts:
                - Conventional Commits
                - Test with Node.js 20
                - Build with Node.js 20
            release-1.3:
              protect: true
              required_status_checks:
                contexts:
                - Conventional Commits
                - Test with Node.js 20
                - Build with Node.js 20
            1.2.x:
              protect: true
              required_status_checks:
                contexts:
                - Conventional Commits
                - Test with Node.js 20
                - Build with Node.js 20
tide:
  merge_method:
    janus-idp/backstage-plugins: squash
  queries:
  - excludedBranches:
    - changeset-release/main
    - changeset-release/release-1.4
    - changeset-release/release-1.3
    - changeset-release/1.2.x
    labels:
    - lgtm
    missingLabels:
    - backports/unvalidated-commits
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - jira/invalid-bug
    - needs-rebase
    repos:
    - janus-idp/backstage-plugins
    reviewApprovedRequired: true
