external_plugins:
  redhat-developer:
  - endpoint: http://needs-rebase
    events:
    - issue_comment
    - pull_request
    name: needs-rebase
approve:
- commandHelpLink: https://go.k8s.io/bot-commands
  lgtm_acts_as_approve: true
  repos:
  - redhat-developer/rhdh-operator
  require_self_approval: true
plugins:
  redhat-developer/rhdh-operator:
    plugins:
    - approve
